[workspace]
resolver = "2"
members  = [
    "types",
    "lexer",
    "parser",
]


[workspace.dependencies]
num       = "0.4.3"
regex     = "1.10.5"
once_cell = "1.19.0"
types     = { path = "types" }
